name = "cv-access"
main = "index.js"
compatibility_date = "2023-10-30"

# For testing, we'll use the workers.dev subdomain
# You can update this with your custom domain later
workers_dev = true

# Define environment variables
[vars]
# These are placeholder values - replace with real values in the Cloudflare dashboard
# or use Wrangler secrets for sensitive information
ALLOWED_ORIGINS = "http://localhost:4000"

# Define secrets (these should be set using wrangler secret commands, not in this file)
# API_KEY - Used to authenticate requests to generate temporary links
# URL_SECRET - Used to sign and verify URLs 