name = "cv-access"
main = "index.js"
compatibility_date = "2023-10-30"

# Production configuration
workers_dev = false

# Custom domain configuration
routes = [
  { pattern = "cv-api.ionel-tech.dev/*", zone_name = "ionel-tech.dev" }
]

# Define environment variables
[vars]
# These are placeholder values - replace with real values in the Cloudflare dashboard
# or use Wrangler secrets for sensitive information
ALLOWED_ORIGINS = "https://ionel-tech.dev"

# Define secrets (these should be set using wrangler secret commands, not in this file)
# API_KEY - Used to authenticate requests to generate temporary links
# URL_SECRET - Used to sign and verify URLs 