name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Debug - Check Environment
        run: |
          echo "Checking if secrets are available..."
          if [ -n "${{ secrets.CV_WORKER_URL }}" ]; then
            echo "CV_WORKER_URL is set"
          else
            echo "CV_WORKER_URL is NOT set"
          fi
          if [ -n "${{ secrets.CV_API_KEY }}" ]; then
            echo "CV_API_KEY is set"
          else
            echo "CV_API_KEY is NOT set"
          fi

      - name: Create _config_secrets.yml
        env:
          CV_WORKER_URL: ${{ secrets.CV_WORKER_URL }}
          CV_API_KEY: ${{ secrets.CV_API_KEY }}
        run: |
          echo "Creating _config_secrets.yml..."
          echo "cv_worker_url: \"$CV_WORKER_URL\"" > _config_secrets.yml
          echo "cv_api_key: \"$CV_API_KEY\"" >> _config_secrets.yml
          echo "Content of _config_secrets.yml (masked):"
          sed 's/\(cv_api_key: \).*/\1"[MASKED]"/' _config_secrets.yml

      - name: Install dependencies
        run: bundle install

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: |
          echo "Building site with Jekyll..."
          bundle exec jekyll build --config _config.yml,_config_secrets.yml --verbose

      - name: Verify build output
        run: |
          echo "Checking generated HTML..."
          if grep -l "data-worker-url" _site/pages/connect/index.html; then
            echo "Worker URL found in generated HTML"
          else
            echo "Worker URL NOT found in generated HTML"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: ionel-tech.dev
          force_orphan: true  # Create a new history for gh-pages branch
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
          full_commit_message: |
            Deploy from ${{ github.sha }}
            
            Changes:
            ${{ github.event.head_commit.message }} 