name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Create _config_secrets.yml
        env:
          CV_WORKER_URL: ${{ secrets.CV_WORKER_URL }}
          CV_API_KEY: ${{ secrets.CV_API_KEY }}
        run: |
          echo "cv_worker_url: \"$CV_WORKER_URL\"" > _config_secrets.yml
          echo "cv_api_key: \"$CV_API_KEY\"" >> _config_secrets.yml

      - name: Install dependencies
        run: bundle install

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --config _config.yml,_config_secrets.yml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: ionel-tech.dev  # Add your custom domain 